### PR TITLE
Entity version with base class

### PR DESCRIPTION
**Pull request by Steit**
An effort to start using a base repository and one default client.

### CODE REVIEW

**Comment by jdeniau** [comment]
I just read it quickly, it seems like a good start. I will try it asap (maybe friday, or next week).

Can you just make it PSR-2 compatible (I saw `_` prefixed variables and one `use` with multiple classes) (you can use [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) to check the violations) .

Thanks

**Comment by jdeniau** [comment]
I had a good look at it, it makes it more simple, that's nice. 

I worked on it to remove useless variables and methods. I will continue on it next week and release a new tag.

**Comment by Steit** [comment]
Good to hear you like my suggestions. I like simple :-)

**Comment by jdeniau** [comment]
Replaced by #21

**Comment by jdeniau** [comment]
I changed some things, feel free to give a look at it, but it's mainly some bug fixes and  small improvements.

Thanks a lot for your PR ;)

**Pull request closed without merging**
